export const LENDERS = 'LENDERS';
export const BORROWERS = 'BORROWERS';
export const GLOBAL = 'GLOBAL';

export const CATEGORIES = {
  LENDERS: 'LENDERS',
  BORROWERS: 'BORROWERS',
  GLOBAL: 'GLOBAL',
};

export const ACTIONS = {
  WALLET: 'WALLET',
  LOAN: 'LOAN',
  OFFER: 'OFFER',
  LIQUIDITY: 'LIQUIDITY',
};

export const LABELS = {
  REPAY: 'REPAY',
  PARTIALLY_REPLAY: 'PARTIALLY_REPLAY',
  REFINANCE_BY_BORROWER: 'REFINANCE_BY_BORROWER',
  INIT: 'INIT',
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  CONNECTED: 'CONNECTED',
  CANCEL: 'CANCEL',
  CREATE: 'CREATE',
};
