export type TransactionType =
  | 'DEPOSIT_LIQUIDITY'
  | 'WITHDRAW_LIQUIDITY'
  | 'LOAN_EXECUTED_BY_BORROWER'
  | 'REFINANCE_EXECUTED_BY_LENDER'
  | 'LOAN_FULLY_REPAID_BY_BORROWER'
  | 'ASSET_SEIZED_BY_LENDER';

export const transactionTypes = {
  DEPOSIT_LIQUIDITY: 'DEPOSIT_LIQUIDITY' as 'DEPOSIT_LIQUIDITY',
  WITHDRAW_LIQUIDITY: 'WITHDRAW_LIQUIDITY' as 'WITHDRAW_LIQUIDITY',
  LOAN_EXECUTED_BY_BORROWER: 'LOAN_EXECUTED_BY_BORROWER' as 'LOAN_EXECUTED_BY_BORROWER',
  REFINANCE_EXECUTED_BY_LENDER: 'REFINANCE_EXECUTED_BY_LENDER' as 'REFINANCE_EXECUTED_BY_LENDER',
  LOAN_FULLY_REPAID_BY_BORROWER: 'LOAN_FULLY_REPAID_BY_BORROWER' as 'LOAN_FULLY_REPAID_BY_BORROWER',
  ASSET_SEIZED_BY_LENDER: 'ASSET_SEIZED_BY_LENDER' as 'ASSET_SEIZED_BY_LENDER',
};
