export type TransactionType =
  | 'LIQUIDITY_DEPOSITED'
  | 'LIQUIDITY_WITHDRAWN'
  | 'LOAN_CREATED'
  | 'LOAN_FULLY_REPAID_BY_BORROWER';
// add more here

export const transactionTypes = {
  LIQUIDITY_DEPOSITED: 'LIQUIDITY_DEPOSITED' as 'LIQUIDITY_DEPOSITED',
  LIQUIDITY_WITHDRAWN: 'LIQUIDITY_WITHDRAWN' as 'LIQUIDITY_WITHDRAWN',
  LOAN_CREATED: 'LOAN_CREATED' as 'LOAN_CREATED',
  LOAN_FULLY_REPAID_BY_BORROWER: 'LOAN_FULLY_REPAID_BY_BORROWER' as 'LOAN_FULLY_REPAID_BY_BORROWER',
  // add more here
};
